### PR TITLE
Add Good Benefits and minor License change

### PR DESCRIPTION
**Pull request by jchiatt**

### CODE REVIEW

**Comment by jchristianhall** [comment]
A few things:
Common practice for open source PRs is to squash commits down into 1. Should we do this?
All of the description text for every page starts with "how to", I think. Should we keep that consistent?

**Comment by jchiatt** [comment]
@jchristianhall Not sure what you mean, but let's definitely chat it through when I'm back.

**Comment by jchiatt** [comment]
Okay, I think we're Good.

**Comment by jchiatt** [comment]
@jchristianhall Testing Good comment.

**Pull request merged**
